version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: sequel
    versions:
    - 5.40.0
    - 5.41.0
    - 5.42.0
  - dependency-name: activesupport
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
    - 1.8.9
  - dependency-name: faker
    versions:
    - 2.16.0
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: puma
    versions:
    - 5.2.1
  - dependency-name: timecop
    versions:
    - 0.9.3
  - dependency-name: dry-schema
    versions:
    - 1.6.0
  - dependency-name: roda
    versions:
    - 3.40.0
  - dependency-name: rubocop-performance
    versions:
    - 1.9.2
  - dependency-name: yard
    versions:
    - 0.9.26
  - dependency-name: rubocop-rspec
    versions:
    - 2.1.0
