require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  EnabledByDefault: true
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'db/schema.rb'
    - vendor/bundle/**/*

Lint/ConstantResolution:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'spec/**/*'

Style/StringHashKeys:
  Exclude:
    - app.rb
    - spec/**/*

RSpec/NestedGroups:
  Max: 5

Layout/LineLength:
  Max: 125
  IgnoredPatterns: ['(\A|\s)#']

Layout/SpaceBeforeBrackets:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'app.rb'

Lint/ToJSON:
  Exclude:
    - app/serializers/**/*

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Naming/VariableNumber:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
